[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
extend_skip = ["papers", "third_party"]

[tool.black]
target-version = ["py37"]
